[package]
name = 'WalletTester'
version = '0.1.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
deploy_account = "_"
